language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7rc6
  - tip

matrix:
  allow_failures:
      - go: tip

install:
  - bash travis/install.sh

script:
  - go build
  - go build _example/sample.go
  - go build _example/sample_grayscale.go
  - go build _example/sample_grayscale2.go
  - go build _example/sample_grayscale3.go
  - go build _example/sample_grayscale4.go
  - go test
