language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

matrix:
  allow_failures:
      - go: tip

install:
  - bash travis/install.sh

script:
  - go build
  - go build example/sample.go
  - go build example/sample_grayscale.go
  - go test
